# Generated by Django 4.0 on 2021-12-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
    ]
